### ISSUE TITLE
Got an error

### ISSUE THREAD

**Issue by hotsu0p** [myferr/aurora-code-editor#1]
/aurora-code-editor-1/src/main.py
Traceback (most recent call last):
  File "c:\Users\joe\aurora-code-editor-1\src\main.py", line 6, in <module>
    from editor import Editor
  File "c:\Users\joe\aurora-code-editor-1\src\editor.py", line 9, in <module>
    from autocompleter import AutoCompleter
ModuleNotFoundError: No module named 'autocompleter'

**Comment by hotsu0p** [comment]
@myferr you there?

**Comment by myferr** [comment]
Sorry this project is no longer maintained!

**Comment by hotsu0p** [comment]
you gave up already @myferr ?

**Comment by myferr** [comment]
Nope, I'll see if I can fix it.
